on:
  push:
    branches:
      - main
      - dev
    tags:
      - '*'
  pull_request:

name: "CI checks"

jobs:
  CI:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [ x86_64 ]
        python-version: [ "3.12" ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Code style & linting
        uses: chartboost/ruff-action@v1
        with:
          src: "./src"
          version: 0.2.1
          args: "check"
      - name: Install dependencies
        run: |
          # Install the package and all the relevant dependencies
          python -m pip install '.[dev]'
      - name: Mypy type checks
        run: |
          mypy src
      - name: Tests
        run: |
          pytest
